name: maker_search
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Collections and utilities functions and classes related to collections.
  collection: ^1.18.0
  # Provides localized string values
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
 # API for HTTP requests
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/